on:
  fork:
  push:
  branches: [ master ]
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened ]
  pull_request_review_comment:
    types: [ created ]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h1>It''s great having you contribute to this project</h1> Welcome to the open-source world :nerd_face:'
          pr-message: '<h1>It''s great having you contribute to this project</h1> Welcome to the open-source world :nerd_face:'
          footer: 'It is really good to see that you have taken out your precious time to contribute to this project. Communication is very important for open-source,please try to communicate well. Any questions?let me know!'
